#Dcokerfile file

FROM gitlab/gitlab-ce:latest

#USER root # want to install some stuff so be GOD!!
#RUN apt-get update && apt-get -y install nodejs
#USER jenkins # drop back to the regular jenkins user!!
